import tkinter as tk

# WIDGET É UM COMPONENTE DA INTERFACE GRÁFICA EX: BOTÃO, CAMPO TEXTO, JANELA

# CONTAINER É UM COMPONENTE QUE PODE TER OUTROS COMPONENTES DENTRO DELE

# WINDOW É UMA JANELA RETANGULAR QUE PODE RECEBER OUTROS COMPONENTES

# TOP-LEVEL-WINDOW É UMA JANELA QUE SOBRPÕE A OUTRA E É INDEPENDENTE

# FRAME É UMA UNIDADE BÁSICA DE ORGANIZAÇÃO DE LAYOUTS COMPLEXOS 

janela = tk.Tk()
janela.title('JANELA PRINCIPAL') # MUDAMOS O TITULO DA JANELA 
janela['bg'] = 'red' # MUDAMOS O BACKGROUND, OU SEJA, A COR DE FUNDO
#L X A + E + T (L = LARGURA, A = ALTURA, E = ESQUERDA, T = TOPO)
janela.geometry('900x400+100+100') # definimos tudo da tela 

# GERENCIDOR DE LAYOUT (SÃO 3 = PLACE / GRID / PACK)

# 1. PLACE = FAZ AS COORDENADAS DO EIXO X E Y 
# 2. GRID = FAZ COMO SE FOSSE UMA TABELA INSERI ROWS AND COLUMNS
# 3. PACK = FAZ O EMPACOTAMENTO NA HORIZONTAL E NA VERTICAL 

lb = tk.Label(janela, text = 'FALA GALERA')
lb.place(x = 100, y = 100)


janela.mainloop() # ESTE COMANDO FAZ UM LOOP E MANTÉM A JANELA ABERTA